version: '2'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=guykert000
      - MYSQL_DATABASE=nueva_estructura
      - MYSQL_USER=desarrollo
      - MYSQL_PASSWORD=guykert000
    ports:
      - 3306:3306




  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=nueva_estructura
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=guykert000
    ports:
      - '5432:5432'

  # postgresql:
  #   image: postgres:9.6
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_DB=nueva_estructura
  #     - POSTGRES_USER=root
  #     - POSTGRES_PASSWORD=guykert000

  # volumes:
  #   postgres-data:
  #     external: false

  # postgres:
  #   image: postgres
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_DB=nueva_estructura
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #   environment:
  #     POSTGRES_PASSWORD: 'guykert000'
  #     POSTGRES_DB: nueva_estructura
  #   ports:
  #     - '8000:8000'

  mongo:
    container_name: container-mongo
    image: mongo
    container_name: global-mongo-service
    restart: unless-stopped

    environment:
      - MONGO_INITDB_DATABASE=nueva_estructura
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=guykert000
    command: ["--bind_ip_all"]
    ports:
      - '27017:27017'
    environment:
        # MONGO_INITDB_ROOT_USERNAME: root
        # MONGO_INITDB_ROOT_PASSWORD: guykert000
        MONGO_INITDB_DATABASE: nueva_estructura